const DEFAULT_PASSWORD_LENGTH = 11;
const EXCLUDED_CHARACTERS = ["0", "o", "O", "1", "I", "l", "q"];
const PASSWORD_LENGTH_MAX = 64;
const PASSWORD_LENGTH_MIN = 4;

export {
  DEFAULT_PASSWORD_LENGTH,
  EXCLUDED_CHARACTERS,
  PASSWORD_LENGTH_MAX,
  PASSWORD_LENGTH_MIN,
};
